### ISSUE TITLE
Some description for RogetThesaurusFeatures? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#100]
There is this feature extractor called: RogetThesaurusFeatures 
Would be nice to have a bit of documentation/explanation what it is.

**Comment by danyaljj** [comment]
Corlex Features are also missing description: https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/765b4e789483817b68bdf320ec7d40266404e163/edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/factory/CorlexFeatureExtractor.java

**Comment by mssammon** [comment]
@yxd126 where do things stand with this issue?

**Comment by mssammon** [comment]
@yxd126 Please look at the documentation for a couple of other feature extractors under the lrec/ package (e.g. https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/765b4e789483817b68bdf320ec7d40266404e163/edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/Affixes.java) 
Please add something similar for the RogetThesaurusFeatures and CorlexFeatureExtractor (description, ideally including a pointer to the original resource the feature extractor is based on; some indication of what the output will be; keywords). Please also make sure there are tests, and that these test the literal string output of the extractor -- see the examples under the lrec tests (e.g. https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/765b4e789483817b68bdf320ec7d40266404e163/edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestAffixes.java)
