### ISSUE TITLE
Move verbsense classifier here 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#103]

**Comment by mssammon** [comment]
@danyaljj from where?

**Comment by danyaljj** [comment]
From here: https://gitlab-beta.engr.illinois.edu/cogcomp/illinois-verbsense 

I should add: and also use it as a dependency to SRL: something to consider after moving SRL to here.

**Comment by lingss0918** [comment]
I moved verbsense here in my branch. Can you give me more detail about dependency to SRL?

**Comment by danyaljj** [comment]
Following the discussion in the group meeting, discuss with @shyamupa on how to evaluate the classifier (and compare it with Dipanjan's classifier and the old SRL in curator).

**Comment by shyamupa** [comment]
I can show how to run dipanjan's classifier, but I did not do the comparison with Christos's classifier (he did it himself and told me the numbers).

**Comment by mssammon** [comment]
sounds like we can go ahead with the merge.  Are there any unit tests for this component?

**Comment by danyaljj** [comment]
@lingss0918 did you make any progress on this?

**Comment by lingss0918** [comment]
Sorry for the late reply, somehow I didn't receive any update notification. 
So do i still need to worry about SRL? 
What unit test do I need to add? Can you be more specific? @mssammon

**Comment by mssammon** [comment]
https://gitlab-beta.engr.illinois.edu/cogcomp/illinois-verbsense/blob/master/src/main/java/edu/illinois/cs/cogcomp/verbsense/VerbSenseLabeler.java
-- this does something to text input.  Create a test that exercises the labeler on a specific sentence/word.

**Comment by lingss0918** [comment]
https://gitlab-beta.engr.illinois.edu/cogcomp/illinois-verbsense/blob/master/src/test/edu/illinois/cs/cogcomp/verbsense/VerbSenseLabelerTest.java
Is this the test you want? @mssammon

**Comment by mssammon** [comment]
yes, this seems fine

**Comment by mssammon** [comment]
@lingss0918 where do things stand with this issue?

**Comment by danyaljj** [comment]
Already done. Closing.
