### ISSUE TITLE
release updated NER

### ISSUE THREAD

**Issue by mssammon** [CogComp/cogcomp-nlp#212]
-- the download on the web site here: http://cogcomp.cs.illinois.edu/page/software_view/NETagger
make sure the correct models are deployed (deploy new ones to maven if necessary)
run the local test to make sure it behaves as expected.

**Comment by mssammon** [comment]
First verify -- and document -- the reported performance and process of generating the performance stats. Clean up scripts if necessary.  Verify that test-linux.sh in scripts/ works (update the reference output text if needed).

**Comment by mssammon** [comment]
@hhuang97 how is this going? any problems?

**Comment by yxd126** [comment]
Has this issue been solved, since this issue was opened in 2016? I think the scripts in the latest NER is all correct. @mssammon

**Comment by cowchipkid** [comment]
@yxd126 Yes, I would say so.
