### ISSUE TITLE
increment minor version? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#228]
it's been a long time that we haven't incremented the minor version, and lots of changes have been made.  Shall we increment the minor? 

Side note: commonly accepted definitions: 

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

**Comment by mssammon** [comment]
After we do some fixes to pos/chunker/ner, I want to release updated packages for these tools. Let's make that the point at which we increase the minor version.
