### ISSUE TITLE
Upgrade the dependencies of big-data-utils 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#239]
Upgrade the dependencies of big-data-utils which is introduced in #119 : 

Quote from Mark: 

> This module uses a very old -- and unsupported -- version of mapdb; http://www.mapdb.org/doc/ and Lucene: https://lucene.apache.org/. It may be worth updating to newer versions

**Comment by cttsai** [comment]
The new mapdb will not be able to read the DBs created by old versions. Will this be a problem?

**Comment by mssammon** [comment]
@cttsai What is the cost of regenerating older mapdb resources? Aside from Wikifier, what projects use the old mapdb?

**Comment by cttsai** [comment]
I don't know what other projects use mapdb. I was worrying the cost would be high if someone is using it. But people can always use an old dependency...so it may be fine.

**Comment by shyamupa** [comment]
I have updated the version for lucene, but mapdb has changed their API dramatically. It will take more time for me  but if its urgent, can someone else take it up?
