### ISSUE TITLE
Remove `slf4j-log4j12` dependency from Core-Utilities

### ISSUE THREAD

**Issue by bhargav** [CogComp/cogcomp-nlp#243]
It is recommended to add slf4j bindings for library projects. The guideline is to let the end-user decide which compatible binding to use. More information in the link below. We should remove the dependency in core-utilities and other library like projects.

http://www.slf4j.org/manual.html#libraries

**Comment by mssammon** [comment]
we can make the implementation dependency 'optional'

**Comment by bhargav** [comment]
Alternatively, we can make the dependency have scope `test`. That way it would not be added transitively to all sub-projects and our unit tests (or other classes under test/) would still generate logs.

We will have to add the `test` dependency on each of the `*/pom.xml` files in our repository.

**Comment by bhargav** [comment]
@mssammon I think this is fixed for core-utilities.

**Comment by mssammon** [comment]
yes, I believe it was fixed in another pull request.  I'll close now.
