### ISSUE TITLE
create a 'thin' illinois-common-resources module

### ISSUE THREAD

**Issue by mssammon** [CogComp/cogcomp-nlp#268]
This would just be a pom.xml and a README that collect the dependencies that used to be all wrapped in the illinois-common-resources jar.   We could later add example code to show how to access information in each resource.  The main purpose is to help us track these resources, so the README should document where the original resources are located.  
This does not have to be a module in illinois-cogcomp-nlp.

**Comment by danyaljj** [comment]
@mssammon do we still want to do this?

**Comment by mssammon** [comment]
Maybe -- depends on whether we move to a different resource deployment model quickly.

**Comment by shatu** [comment]
Sorry, didn't realize that I had this issue assigned to me. Let me know what you guys decide about this and how you want me to do this.

**Comment by mssammon** [comment]
@shatu please go ahead with this. We're hesitant to move straight to minio, so this is worthwhile.

**Comment by danyaljj** [comment]
So in the light of #403, do we still want to move on with this, @mssammon ?

**Comment by mssammon** [comment]
I guess we moved faster than I thought we would -- the thin resources project no longer seems necessary.
