### ISSUE TITLE
OpenIE of CoreNLP for the pipeline? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#326]
Stanford CoreNLP has [OpenIE module](http://stanfordnlp.github.io/CoreNLP/openie.html) which seem to be working fairly good. Maybe we add an annotator wrapper for this module?

**Comment by danr-ccg** [comment]
What functionalities are included in this OpenIE?

              Dan

**Comment by danyaljj** [comment]
Already in the externals. Closing it ....
