### ISSUE TITLE
Python module to call the pipeline

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#338]
Write simple python modules to make calls to the pipeline server and do stuff like; 

 - tokenize 
 - POS tag 
 - NER 
...

**Comment by danyaljj** [comment]
Discussed it with Dan. He'll prolly assign it to an undergrad.

**Comment by danr-ccg** [comment]
I talked this morning with a group of students that will work on that.
Who will be guiding them in this project?

              Dan

**Comment by danyaljj** [comment]
Great. @bhargav and I can help guiding it.

**Comment by danyaljj** [comment]
Already started in Sioux. Closing it.
