### ISSUE TITLE
Running the Servers

### ISSUE THREAD

**Issue by jeffrschneider** [CogComp/cogcomp-nlp#362]
I'm having a hard time trying to run the various servers, see:
http://cogcomp.cs.illinois.edu/curator/servers/ 

Can you point me to the source files for them? I'm not seeing them in github  or in the docs:
http://cogcomp.cs.illinois.edu/software/doc/apidocs/ 

Also, I saw that at least one of them (Pipeline) commented that it was only tested on Ubuntu; do we know if they work on Windows?

**Comment by danyaljj** [comment]
Did you try using the pipeline? 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/pipeline

**Comment by jeffrschneider** [comment]
Hmm. I primarily focused on Curator, and then I tried a couple other servers (Pipeline wasn't one of the server options I saw listed). I'm happy to try that if that's what is working. Also, per the last question - any idea if it works on Windows?

**Comment by danyaljj** [comment]
Def give the pipeline a try. 

Windows: as far as I'm aware, it should work smoothly.

**Comment by danyaljj** [comment]
If not resolved, reopen it.
