### ISSUE TITLE
Idea: Move Artifact Deployment to Jenkins CI

### ISSUE THREAD

**Issue by bhargav** [CogComp/cogcomp-nlp#382]
We can move the artifact deployment to Jenkins CI. Should be more stable than doing it on Semaphore?

https://wiki.jenkins-ci.org/display/JENKINS/ArtifactDeployer+Plugin

**Comment by mssammon** [comment]
is deployment from semaphore a problem, once the CI build completes successfully?

**Comment by bhargav** [comment]
Semaphore builds seem to fail too often due to Network/Download issues. Jenkins on morgoth has been more reliable in my opinion.

**Comment by bhargav** [comment]
Artifact Deployment is now enabled in Jenkins.

**Comment by mssammon** [comment]
+1
