### ISSUE TITLE
Make ProtocolBuffers the default binary serialization

### ISSUE THREAD

**Issue by bhargav** [CogComp/cogcomp-nlp#399]
- Update [SerializationHelper](https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/SerializationHelper.java) to make Protocol Buffers the default for [`serializeToBytes`](https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/SerializationHelper.java#L78) method. 

This breaks backward compatibility and thus needs to be part of a major release version.

**Comment by mssammon** [comment]
@danyaljj @cowchipkid confirming that we decided that this is *not* what we want to do -- serialization to json is preferred.  Right?

**Comment by danyaljj** [comment]
Yeah, I prefer json as well. 

But it's important for everyone to know that there is a protobuff serialization too.

**Comment by cowchipkid** [comment]
Yes, I would prefer json.
