### ISSUE TITLE
Documentation for Java API

### ISSUE THREAD

**Issue by mortezakz** [CogComp/cogcomp-nlp#400]
Hi,

I downloaded the latest (stable?) version 3.0.23 from:

https://cogcomp.cs.illinois.edu/page/download_view/NETagger

I cannot find the documentation, and the Read Me file is to thin on details. I want to call the NER on a string, have entities tagged, and get the entities as well as their positions in text. I use Java.

I noticed the Github Read Me is more detailed, but cannot be used with the 3.0.23 version. 

I know I can probably download the latest version from Github and build a .jar (that is, if the Github version is tested), but  I thought I would ask to see if there is documentation for the 3.0.23 version or a dist jar for the latest version already. 

Thank you.

**Comment by danyaljj** [comment]
The latest version on github is 3.0.106: https://github.com/CogComp/cogcomp-nlp/blob/master/ner/pom.xml#L8 

Can you give it a try?

**Comment by mortezakz** [comment]
Used Maven within Eclipse and Netbeans, and get  different Maven build errors in both. Something seems to be wrong in the POM, but I will not have time tonight to debug. Thank you for your reply. I will let you know how it goes.

**Comment by mortezakz** [comment]
The POM problem for your preview. It's also unclear from the documentation  what dependencies are required by the NER module to run (I am guessing it means ALL the jars in the target dependency folder as collected by Maven)
![error](https://cloud.githubusercontent.com/assets/11914617/24086201/a4eb343c-0ce1-11e7-93c6-f9296cf2ffe7.JPG)

**Comment by danyaljj** [comment]
This error is not related to our project. Your maven project does not have a "build" cycle. 


 > It's also unclear from the documentation what dependencies are required by the NER module to run (I am guessing it means ALL the jars in the target dependency folder as collected by Maven)

The whole point of maven (and other dependency management tools) is that you don't have to worry about the dependencies, because they are all managed by the system. Same is true here. You just have to add NER and the rest will be downloaded by maven.

**Comment by mortezakz** [comment]
Thank you, Daniel. I actually made that work ultimately - my apologies for not replying. Though now I get the following error when trying to run the example included in your Reed Me. 

9:42:58 ERROR NERAnnotator:161 - Cannot annotate the text, the exception was: 
java.lang.NullPointerException
    at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.ExpressiveFeaturesAnnotator.annotate(ExpressiveFeaturesAnnotator.java:71)
    at edu.illinois.cs.cogcomp.ner.NERAnnotator.addView(NERAnnotator.java:158)
    at testing.main(testing.java:36)
Exception in thread "main" java.lang.IllegalArgumentException: View NER_CONLL not found
    at edu.illinois.cs.cogcomp.core.datastructures.textannotation.AbstractTextAnnotation.getView(AbstractTextAnnotation.java:134)
    at testing.main(testing.java:38)

My own project is not a Maven project (it's a Play Framework project that I am avoiding to use Maven with, for several reasons) - that's why I said, ideally I would just use the NER jar instead. 

I very much appreciate your explanations. 




    On Monday, March 20, 2017 8:57 AM, Daniel Khashabi <notifications@github.com> wrote:
 

 This error is not related to our project. Your maven project does not have a "build" cycle.
It's also unclear from the documentation what dependencies are required by the NER module to run (I am guessing it means ALL the jars in the target dependency folder as collected by Maven)
The whole point of maven (and other dependency management tools) is that you don't have to worry about the dependencies, because they are all managed by the system. Same is true here. You just have to add NER and the rest will be downloaded by maven.—

**Comment by danyaljj** [comment]
@mortezakz even if you're using play framework you should use sbt package manager. 

The error says that your current `TextAnnotation` object does not have the NER view. 
I recommend you take a look at our pipeline and its usage: https://github.com/CogComp/cogcomp-nlp/tree/master/pipeline

**Comment by mortezakz** [comment]
@danyaljj  Back then when I posted this issue, We did try sbt or even Maven using:

<artifactId>illinois-cogcomp-nlp</artifactId>
<groupId>edu.illinois.cs.cogcomp</groupId>
<version>3.0.106</version> 

And it did not work. The error was that it could not find the jar file. It seems at one point you had the jar in the maven repositories but then removed it (might be because of the build errors?)

I suggest you test it yourself, in a test Maven project. 

Thank you for your assistance though. I will wait to see if there is any update on GitHub. I'll use Stanford NER for now.

**Comment by danyaljj** [comment]
Can you share a pointer to your code?

**Comment by mortezakz** [comment]
I should have included the CogComp repository too, as pointed out int the main NLP project Read Me (it's not mentioned in the NER module readme, which was the source of confusion). 

Also, the example you provide in the NER readme  uses IllinoisTokenizer which seems to be deprecated. 

I tried running the example code included in the NER readme, and get the following error now. I increased memory to  -Xms512m -Xmx2048m and still get the same error. 

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.toLowerCase(Unknown Source)
	at java.lang.String.toLowerCase(Unknown Source)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers$1.split(TreeGazetteers.java:74)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteerTree.readDictionary(GazetteerTree.java:356)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:103)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:48)
	at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:312)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:57)
	at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:103)
	at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:125)
	at CogGroup.TestArtifact.App.main(App.java:34)

**Comment by danyaljj** [comment]
> Also, the example you provide in the NER readme uses IllinoisTokenizer which seems to be deprecated.

Good point. Opened a separate issue for that. 

> I tried running the example code included in the NER readme, and get the following error now. I increased memory to -Xms512m -Xmx2048m and still get the same error.

I think you need around 3.5GB for running NER. 
@cowchipkid am I right here?

Also, give this a try: 
https://github.com/CogComp/cogcomp-nlp/tree/master/pipeline#java-client

**Comment by cowchipkid** [comment]
@mortezakz @danyaljj  I have been running NER stuff with around 4G. The memory requirements increased markedly when we last updated the gazetteers.

**Comment by mortezakz** [comment]
Thanks @danyaljj  and @cowchipkid . With that kind of memory requirement, it does make sense for me to set up a server and run the script to set up the server. Where can I download the Pipeline? The documentation says "Assuming you downloaded the pipeline package as a zip from the Illinois Cognitive Computation Group's web site."
Would you clarify the download link?

**Comment by danyaljj** [comment]
If you want to give it a try, use this server: 
`http://austen.cs.illinois.edu:8080`

Sample: austen.cs.illinois.edu:8080/annotate?text="This is a sample sentence. I%27m happy."&views=POS,NER_CONLL 

If you want to run your own server, here is the instruction: https://github.com/CogComp/cogcomp-nlp/tree/master/pipeline#using-pipeline-webserver

**Comment by mortezakz** [comment]
Thanks. I hate to keep asking more questions, but how can I get the  token_start_offset for each token? Is it possible in the server output? 
My goals is to get the start offset of persons, locations etc. I'll open a new issue if necessary.

**Comment by danyaljj** [comment]
Use this: 
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/Constituent.java#L373

```
        for (Constituent c : ta.getView(ViewNames.NER_CONLL).getConstituents()) {
            int tokenId = c.getStartSpan();
       }
```

**Comment by mortezakz** [comment]
Thanks. c.getStartCharOffset() is what I'm looking for :-)

**Comment by mssammon** [comment]
@mortezakz can we close this issue?

**Comment by mortezakz** [comment]
Yes! I very much appreciate your help folks. Also, FYI, I believe the NER needs at least 6g Xmx.  Thanks again. 
 

    On Tuesday, April 11, 2017 12:07 PM, Mark Sammons <notifications@github.com> wrote:
 

 @mortezakz can we close this issue?—
