### ISSUE TITLE
[pipeline] script doesn't exist. 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#446]
In the pipeline docs:
https://github.com/CogComp/cogcomp-nlp/tree/master/pipeline#running-a-simple-command-line-test
 `runPreprocessor.sh` is mentioned, but it doesn't exist in the scripts folder.

**Comment by mssammon** [comment]
The README describes the (now outdated) self-contained package.  I could update the instructions to be based on the maven project, requiring users to run `mvn install` and `mvn dependency:copy-dependencies`, or running a maven command to execute the relevant main class. Or, I could leave it as is.
Thoughts, @danyaljj, @cowchipkid , @bhargav ?

**Comment by danyaljj** [comment]
I'd update for updating it (i.e. run through the maven project)

**Comment by mssammon** [comment]
I made this change in the ERE event reader PR.
