### ISSUE TITLE
Fatal error while evaluating classifier ConstrainedPrepSRLClassifier

### ISSUE THREAD

**Issue by gkiril** [CogComp/cogcomp-nlp#458]
Suppose I have the following code for PrepSRL:

```
Preprocessor preprocessor = new Preprocessor(PrepSRLConfigurator.defaults());
Annotator` annotator = new PrepSRLAnnotator();
String longSentence = "That put him a stroke ahead of Curt Byrum, John Adams and " + 
                      "Lonnie Clements , all of whom are looking for their first " + 
                       "victory on the PGA Tour .";
TextAnnotation ta = TextAnnotationUtilities.createFromTokenizedString(longSentence);
preprocessor.annotate(ta);    
View view = annotator.getView(ta); // ERROR HERE!
```
On the last line (line 75 in my code), I get the following error:

```
ILP ERROR: Unsatisfiable constraints!
LBJava ERROR: Fatal error while evaluating classifier ConstrainedPrepSRLClassifier: edu.illinois.cs.cogcomp.lbjava.infer.InferenceNotOptimalException: Failed to solve inference problem with the following head object: ahead of
edu.illinois.cs.cogcomp.lbjava.infer.InferenceNotOptimalException: Failed to solve inference problem with the following head object: ahead of
	at edu.illinois.cs.cogcomp.lbjava.infer.ILPInference.infer(ILPInference.java:237)
	at edu.illinois.cs.cogcomp.lbjava.infer.ILPInference.valueOf(ILPInference.java:276)
	at edu.illinois.cs.cogcomp.prepsrl.inference.ConstrainedPrepSRLClassifier.discreteValue(ConstrainedPrepSRLClassifier.java:76)
	at edu.illinois.cs.cogcomp.prepsrl.PrepSRLAnnotator.addView(PrepSRLAnnotator.java:85)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:181)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:166)
	at Demo.main(Demo.java:75)
```
How can this be fixed? I tried catching both the `InferenceNotOptimalException` and the generic `Exception` (quick dirty fixes), but that didn't work out.

**Comment by danyaljj** [comment]
Currently there is no easy short-term fix for this, except skipping this sentence.  
We have to revise PrepSRL to see what's going on (@christos-c?).

**Comment by gkiril** [comment]
Yes, but how do I skip sentences like this? Whenever I process a corpus, when I get to a sentence like this - the program would break (since catching is not an option here).

**Comment by gkiril** [comment]
Update: I took a sample of 1000 sentences from the [New York Times corpus ](https://catalog.ldc.upenn.edu/ldc2008t19) and 47 sentences (roughly 5% of the sample) were throwing this error, which means that this is not that of a rare problem. I tried with try/catch:
```
catch (Error  e) { } 
catch (Exception e) { }
catch (RuntimeException e) { }
catch (Throwable e) { }
```
but the exception is still thrown. Can you suggest at least a dirty work-around which will just skip sentences which provoke such behavior?

**Comment by mssammon** [comment]
Without looking at the prep srl code -- which will take me a while -- I'm guessing there's an ```assert``` somewhere in the call stack.  Try adding ```catch (AssertionError e) {}```...

**Comment by gkiril** [comment]
Thanks for the answer. However, even with `catch (AssertionError e) {}` the same happens (the exception is not caught).

**Comment by bhargav** [comment]
So I looked at the code flow and the behavior you see is because of a `System.exit(1)` statement when the inference throws an Exception. Here at https://github.com/CogComp/cogcomp-nlp/blob/master/prepsrl/src/main/java/edu/illinois/cs/cogcomp/prepsrl/inference/ConstrainedPrepSRLClassifier.java#L82

Ideally, the correct behavior would be to return the highest scored label for the local classifier when the ILP Inference fails.

**Comment by christos-c** [comment]
Apologies for taking so long to address this problem. I'm testing @bhargav's proposed solution and I'll be sending a PR later today.

**Comment by danyaljj** [comment]
New version is deployed now. @gkiril want to give it a try?
