### ISSUE TITLE
View that doesn't contains substrings 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#472]
Suppose you want to keep paraphrases of each phrase as an extra view. Current we're assuming that in each view, the constituents are sub-strings of the original text. But sometimes it is not the case: e.g. the example that I gave: paraphrases of the original text. 
@mssammon @bhargav  and others: Thoughts on what is the best way to represent such information?

**Comment by cogcomp-dev** [comment]
Is the problem that you might have paraphrases that cover non-contiguous elements of the original text? If so, you might use a predicate argument structure, where arguments are sequences from the original text, and the predicate contains the corresponding paraphrase; its offsets might correspond to the root (highest element in parse tree?) of the source text elements.

Mark

**Comment by danyaljj** [comment]
I think the problem is **not** having to "cover non-contiguous elements of the original text". The issue is that my annotation might not have any coverage with the original text. 
Like I'm creating an annotator for [ClausIE](https://gate.d5.mpi-inf.mpg.de/ClausIEGate/ClausIEGate), where it gets a sentence and gives your simplified sentences: 
```
INPUT: 
Bell, a telecommunication company, which is based in Los Angeles, makes and distributes electronic, computer and building products.

OUTPUT: 
"Bell is a telecommunication company"
"Bell is based in Los Angeles"
"Bell makes electronic products"
"Bell distributes electronic products"
```

**Comment by cogcomp-dev** [comment]
Maybe you need a tree view, possibly referring to constituents of a syntactic parse:

TextAnnotation rep:
Text

Bell, a telecommunication company, which is based in Los Angeles, makes and distributes electronic, computer and building products.

Some parse view, partially represented:


(NP Bell) , (NP a telecommunication company) , (WDT which) (VP is based) (PP in Los Angeles) , (VP makes) and (VP distributes) (NP electronic, computer and building products).


New Entailed  Assertions view:

Predicate: (ENTS "Bell is a telecommunication company")

Args: (NP Bell)  (PRED ,)  (NP a telecommunication company)

<here, all the args are children of the predicate>



Predicate: (ENTS "Bell makes electronic products")

Args: (NP Bell) (PRED makes) (MOD electronic) (NP products)

<here, ‘electronic’ should modify ‘products’, not be attached to the predicate>

Offsets of args derive from whatever view you take them from.
Offsets of predicate are up for grabs, but could be the longest span, or just the source of the main predicate (in this case, the comma).

You could back off from the syntactic structure and express that the arguments should be interpreted only as indicating the spans in the source text from which the derived assertion emerged, i.e. that they don’t necessarily represent arguments or  syntactic structure.

Mark

**Comment by danyaljj** [comment]
When you say `Predicate: (ENTS "Bell is a telecommunication company")`, how [would you define this constituents](https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/Constituent.java#L66-Lundefined
)?  Like how would you put for `begin` and `end` token ids?  Currently we assume that all the constituents (predicate, argument, etc) are substrings of the original text. (the original text says "Bell, a telecommunication company, ... ")

**Comment by danyaljj** [comment]
One alternative is this: 
 - Create a constituents for each sentence and add these outputs as attributes of the corresponding sentence.

**Comment by mssammon** [comment]
for token ids, either pick the longest span based on source text, or pick a "main predicate" span from the source text. Probably the former is more intuitive.

**Comment by mssammon** [comment]
the attributes approach seems messy. you will need to either generate one potentially very long attribute value that must be parsed to identify components -- assuming there are generally >1 entailed assertions -- or you have to autogenerate keys and parse those instead.

**Comment by danyaljj** [comment]
Makes sense ...
