### ISSUE TITLE
NER: output of lbjava

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#485]
@cowchipkid have you checked in these files intentionally? 
https://github.com/CogComp/cogcomp-nlp/tree/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/LbjFeatures

**Comment by cowchipkid** [comment]
I have no idea how I managed to get these checked in again. I will delete them with the next PR.

**Comment by danyaljj** [comment]
Thanks @cowchipkid . Plz close this after addressing it.

**Comment by Slash0BZ** [comment]
I will delete these files in the next PR.

**Comment by cowchipkid** [comment]
I have already deleted these in my local repository, that change will be in my next PR which is just about ready.
