### ISSUE TITLE
MapDB: where to do commit 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#487]
In `TextAnnotationMapDBHandler`  don't we need to commit after each [`put`](https://github.com/CogComp/cogcomp-nlp/blob/0beedbdc8a9fa150b2eafa446460340007d31168/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/io/caches/TextAnnotationMapDBHandler.java#L77) and [`replace`](https://github.com/CogComp/cogcomp-nlp/blob/0beedbdc8a9fa150b2eafa446460340007d31168/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/io/caches/TextAnnotationMapDBHandler.java#L88)? 
It might slow down the system, but at least upon program crash, the db file won't be empty. Am I right @mssammon ?

**Comment by danyaljj** [comment]
In fact I think this is the likely reason for #443

**Comment by mssammon** [comment]
@danyaljj I think you are right -- I think if someone activates the cache they have to live with it being a little slower in the name of higher reliability.

**Comment by danyaljj** [comment]
Added the fix to #488.
