### ISSUE TITLE
Usage Help: Cannot replicate the result from the demo page

### ISSUE THREAD

**Issue by pastoref** [CogComp/cogcomp-nlp#493]
Hope I'm writing in the right place.

I'm using the pipeline to process the sentence

"The system sets VoltageLowError as not detected."

If I use the demo
http://cogcomp.cs.illinois.edu/page/demo_view/SRL
the processing leas to two distinct SRLs

one is "The system sets VoltageLowError"
the other is "VoltageLowError as not detected."

When I use the Java API, I get only a single result. How does your implementation split the sentences?

Also, in my implementation "VoltageLowError as not detected" is indicated as A1 for verb "set", while on the web just "VoltageLowError" is A1. Do I need to use a specific comnfiguration?

I invoke the method:
pipeline.createAnnotatedTextAnnotation( docId, textId, text );

This is my configuration:
isSentenceLevel true
stanfordMaxTimePerSentence  1000
stanfordParseMaxSentenceLength  60
simpleCacheDir simple-annotation-cache
usePos  true
useLemma    true
useShallowParse true
useNerConll true
useNerOntonotes true
useStanfordParse    true
useStanfordDep  true
useSrlVerb  true
useSrlNom   false

Thanks is advance for any pointer.
Also, is it possible to programmatically invoke your web interface?

**Comment by danyaljj** [comment]
Which java code are you using?
Have you tried this demo? http://deagol.cs.illinois.edu:8080/

**Comment by mssammon** [comment]
The SRL demo uses a different version of the SRL code that uses the Charniak syntactic parser.  This is not something we can easily distribute, so the pipeline uses the Stanford syntactic parser instead. This leads to differences in behavior.

**Comment by pastoref** [comment]
Thank you both for the reply.

The demo you suggest is currently not working but I''ll try later.

Last point, is there any mean to  programmatically invoke your web interface? (different than parsing the html of course).

Thanks

**Comment by mssammon** [comment]
You can install the Curator package: http://cogcomp.cs.illinois.edu/page/software_view/Curator
this is not a trivial undertaking.

**Comment by danyaljj** [comment]
+ you can access pipeline endpoint here: 
http://austen.cs.illinois.edu:8080/annotate?text=%22This%20is%20a%20sample%20sentence.%20I%27m%20happy.%22&views=SRL_VERB
which has query limit. But you can install this end-point on your machine too; more here: https://github.com/CogComp/cogcomp-nlp/tree/master/pipeline#server-clients

**Comment by pastoref** [comment]
Thank you a lot for the URL it fits all my needs. I had tried to use the end-point on my machine by I remember that it was not providing some Views, but maybe I was trying to use the SRL_NOM View which I am not considering anymore.

Thanks again
