### ISSUE TITLE
How to cache a TextAnnotation?

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#494]
@mssammon What is our preferred way of caching annotated data? 
Options 1: TextAnnotation-level caching: 
 - Key: encoding ( TextAnnotation.text + TextAnnotations.getAvailbleViews()) 
 - Value TextAnnotation in byte[]  format 

Option 2: View-level caching: 
 - Key: encoding (text + view-name) 
 - Value View in byte[]  format (we don't have serialization for Views, but I think we should be able to do a a little refactoring to do this). 

Any other option I'm missing?

**Comment by mssammon** [comment]
@danyaljj this is somewhat up for grabs.  Current model is TextAnnotation-level caching: if views are updated, they are added to the TextAnnotation retrieved from cache and then the cache is updated.
