### ISSUE TITLE
NER view names

### ISSUE THREAD

**Issue by mortezakz** [CogComp/cogcomp-nlp#507]
In the NER readme, some F1 numbers are reported for different models. Would you clarify their view names maybe in the same table?

ViewNames.NER_CONLL looks to be CoNLL only. What's Enron and what's Enron + CoNLL?

Thank you.

**Comment by mssammon** [comment]
NER_CONLL means "PER/LOC/ORG/MISC" are the candidate labels, and these labels are the same for Enron + CoNLL.  You specify the model to use, which populates a view with the corresponding labels.

**Comment by mortezakz** [comment]
Oh I see - where do I specify the model in the Java Code (or configurations? In other words, how do I know which model I'm running?

**Comment by mssammon** [comment]
At present, is it determined by which dependency you specify in your pom file, and which configurator you use.  If you want the classifier trained only on conll data, specify the appropriate version (3.1) and maven classifier (CoNLL) in your pom -- the ner pom does this for the CoNLL + Enron model here: [https://github.com/CogComp/cogcomp-nlp/blob/master/ner/pom.xml#L78] 
You will also need to specify the model name to override the default in [NerBaseConfigurator](https://github.com/CogComp/cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/config/NerBaseConfigurator.java). The Ontonotes configurator does this here:
https://github.com/CogComp/cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/config/NerOntonotesConfigurator.java#L37
-- you need the value "CoNLL" for the model name parameter.
I'll create an issue to clarify this in the documentation.

**Comment by mortezakz** [comment]
This is a little confusing. All I do is include  "edu.illinois.cs.cogcomp" % "illinois-ner" % "3.1.24" (and reference your repository). So there is no flexibility unless I get the source code and modify those params, right?
In that case, what NER version (3.1.24) use, and what does the (3.1.10) use?

Thank you.

**Comment by mssammon** [comment]
each model has a set of classifiers/lexicons with a distinct prefix.  When you set the value for the model name as a property that you pass to the base configurator's getConfig() method, you are specifying the relevant model files. They will only be on the path if you have added the relevant dependency.

**Comment by danyaljj** [comment]
I suppose this issue is resolved. Closing for now ..
