### ISSUE TITLE
[NER]How to get the listed performances for NER

### ISSUE THREAD

**Issue by LiuShifeng** [CogComp/cogcomp-nlp#516]
I use scripts/runNER.sh to tag conll03 using default setting.
However, the result is not as the posted one when estimated in entity level.
I also use scripts/train.sh to train one for conll03 dataset (config file is similar to reuters-noise.config).
Still, the performance is far away from the posted one.
**Is the performance estimated in token level or entity level?**
OR **Any settings to get the posted performance?**
**Are there any settings to train an identical classifier as the distributed one?**
Thank you!

**Comment by cowchipkid** [comment]
For CoNLL, we report the F1 value for entity level tagging. What version of the library are you using? What training data are you using? I have not used train.sh for some time, I use the benchmark.sh script to build my models. I think reuters-nonoise is the right one to use.

**Comment by LiuShifeng** [comment]
Hi cowchipkid, 
Thank you for your reply!
The library is the one distributed on github, and the model I use is CoNLL_enron version 3.3.
For the training data, I use conll03.eng.train and conll03.eng.testa for my own construction.
I'll try benchmark.sh as your sugguestion

**Comment by cowchipkid** [comment]
I have no idea what’s in those datasets, I have a set that I use I can provide that to you if you would like.

How much do your results differ from what’s published?

**Comment by LiuShifeng** [comment]
It's about 82.9F1 on conll03/testb/, nearly 8 f1 score below the published one.
I'm checking my code currently.

For the dataset, if you can provide me, that would be great! 
I can do more experiments with it.
Thank you so much.

**Comment by cowchipkid** [comment]
Sure, I have created a benchmark directory in my home directory on shelley. In the benchmark directory, you will find 3 different data directories. One is the CoNLL data directory we have used to build the standard CoNLL models, and then there are two other directories, both including the same data (both Enron and CoNLL data) but different learning rates and thicknesses. On dataset was used to test against enron hold-out set, the other was used to test against a CoNLL hold out set. You can take you pick or train against all of that as you please.

**Comment by danyaljj** [comment]
@LiuShifeng  is this an issue? If so, plz open it.
