### ISSUE TITLE
illinois-srl uses old version of data-store

### ISSUE THREAD

**Issue by Slash0BZ** [CogComp/cogcomp-nlp#522]
I encountered the separator error on Windows  when running pipeline test "StringTransformationOffsetTest", where the illinois-srl downloads levin from data-store. Please check.

**Comment by danyaljj** [comment]
Do you have a code that we can reproduce this issue?

**Comment by Slash0BZ** [comment]
I have found the issue: edison explicitly relies on cogcomp-datastore:1.9.7 https://github.com/CogComp/cogcomp-nlp/blob/master/edison/pom.xml#L94, which uses the old code before the fix, I checked the code ran by edison and it was in fact the buggy code. Should I change it to 1.9.9?

**Comment by danyaljj** [comment]
Good catch. Send a separate PR for it?
