### ISSUE TITLE
version increment script not working for subfolders

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#529]
https://github.com/CogComp/cogcomp-nlp/blob/master/increment-pom-versions.sh
is not working for subfolders. Specifically for submodules inside the `external` folder.

**Comment by danyaljj** [comment]
Can you have a look at this @Slash0BZ ?

**Comment by Slash0BZ** [comment]
I tried to run the script from the root twice and I can verify that it works on subfolders under external/ every time. Can you describe a little more on the condition/environment on which you encountered the problem? Thanks

**Comment by danyaljj** [comment]
Oh nvm it might be my mistake when checking them into git. 

Closing it ....
