### ISSUE TITLE
Typo Error of the default OntoNotes config file in the benchmark folder

### ISSUE THREAD

**Issue by yxd126** [CogComp/cogcomp-nlp#533]
https://github.com/CogComp/cogcomp-nlp/blob/fb33e2e78b8fcd871c445c85f7e61b6a66a45b5a/ner/benchmark/Ontonotes/config/ontonotes.nonoise.config#L6

https://github.com/CogComp/cogcomp-nlp/blob/fb33e2e78b8fcd871c445c85f7e61b6a66a45b5a/ner/benchmark/Ontonotes/config/ontonotes.noise.config#L6

In these two files, between type Date and type Event, space is missing. If one uses these two config files to train the model, then we will have a label called DateEvent, but no label Date or Event.

**Comment by cowchipkid** [comment]
This is fixed in the newest release.
