### ISSUE TITLE
In `TextAnnotationUtilities. copyViewFromTo ` always add the view even if it's empty  

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#546]
Here I think we shouldn't have this if condition. Even if the view is empty, we should add it. 
https://github.com/CogComp/cogcomp-nlp/blob/a39d82de29bb638dff3c2f78a79d6e9250418486/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/TextAnnotationUtilities.java#L259

Here is the current issue happening to me. Consider this sentence: 

"It's well."

There is no NERs in this sentence, so NER returns no constituents. With this pattern, we do not populate any NER view (which logically is different from having an empty NER). And I'm running SRL_VERB in the downstream which expects NER view (even if it's empty), but since there no NER view it throws exception. 

@mssammon Do you think it's fine to drop `if` in the line I pointed out?

**Comment by mssammon** [comment]
agreed -- this makes sense.
