### ISSUE TITLE
How to pass run-time parameters to Annotators?

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#548]
@mssammon any thoughts on what is a best way to pass a run-time parameter to an Annotator? 
@666666fzl has this annotator for temporal package, which could [optionally] accept an extra parameter indicating "document creation time". Is there a clean way to pass parameters to Annotators? (for initialization I know we can use ResourceManager). 

How about we create a `addView` function (optional to implement) such that also accepts a `ResourceManager` object?

**Comment by mssammon** [comment]
Two initial options: 
1) Use a property in the TextAnnotation's attribute field when passing it to `getView()`
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/TextAnnotation.java#L65
2) define an explicit argument to pass to getView() that is common to all Annotators; could be a map. 

2) is probably cleaner; 1) runs the risk that two different annotators write to the same key in the attributes dictionary. @cowchipkid what do you think?

**Comment by cowchipkid** [comment]
I would vote #2. #1 breaks polymorphism since other possible future implementations of TextAnnotation would not carry the same feature. Also, decoupling the act of setting an attribute in the annotator from the single method call that would be the only one to use said attribute might be a bit confusing.

**Comment by mssammon** [comment]
one problem with this is that it potentially breaks backwards compatibility.  We could alleviate by having two getView() calls -- the current one calling the new method with an empty attribute map.  Do either of you see any problems with this? @cowchipkid @danyaljj

**Comment by cowchipkid** [comment]
I see no problem with this.

**Comment by mssammon** [comment]
The only difficulty, I think, is that all previous annotators still need to change to the new `addView()` with the attributes argument. Otherwise we will have duplication/redundancy. 
We should also think about the way attributes are handled across multiple annotators.  I'm inclined to have an `AttributeNames` class comparable to `ViewNames`, where each annotator in the cogcomp-nlp project defines its particular attributes, as a way to try and avoid inadvertent replication of attribute names by different annotators, where the attribute values might be different.

**Comment by danyaljj** [comment]
That sounds reasonable to me. Also, would be good if we distinguish (at least in the naming) "run-time" vs load-time (initialization) parameters/attributes.

**Comment by danyaljj** [comment]
How about an slightly different approach: 

```java
   /**  
       Add the content of the annotators to a given TextAnnotation object. 
       @param runtimeAttributes the parameters that might change the behavior of the annotator while after initialization and while running. 
    */ 
    protected abstract void addView(TextAnnotation ta,  ResourceManager runtimeAttributes) throws AnnotatorException {
        throw new NotImplementedException("This annotator does not accept run-time attributes. You have to run `addView() function without the attributes parameter. `");
    }
```

This way we don't have to implement it for all the Annotators we have (we overrirde it wherever we need it). 
About creating `AttributeNames` class: I don't have any opinion. Not sure if we have that many run-time parameters, but it might help over time.

**Comment by mssammon** [comment]
In the context of the pipeline, I assume that the default will be to assume parameters -- in which case, the new `addView()` method should by default log the message and call the basic `addView()`.  Seem reasonable?

**Comment by danyaljj** [comment]
Like this? 
```java
   /**  
       Add the content of the annotators to a given TextAnnotation object. 
       @param runtimeAttributes the parameters that might change the behavior of the annotator while after initialization and while running. 
    */ 
    protected abstract void addView(TextAnnotation ta,  ResourceManager runtimeAttributes) throws AnnotatorException {
        logger.warn("This annotator does not accept run-time attributes. You have to run `addView() function without the attributes parameter. `");
       return addView(ta); 
    }
```

**Comment by mssammon** [comment]
right, but it should not be an abstract method.  Those annotators that require runtime attributes can override this method, but the definition above suffices for the majority of annotators as is.

**Comment by danyaljj** [comment]
Right it shouldn't be abstract. Fixed my comment.

**Comment by mssammon** [comment]
@cowchipkid  any objections?

**Comment by cowchipkid** [comment]
No objections.

**Comment by danyaljj** [comment]
@mssammon the same thing should be implemented for BasicAnnotatorService too; right? 
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/annotation/BasicAnnotatorService.java#L298

**Comment by mssammon** [comment]
Yes -- together with changing AnnotatorService, whose abstract methods BasicAnnotatorService is implementing.
