### ISSUE TITLE
Char offsets in the json file 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#554]
Currently we don't have char offsets in the json file. (here an example [output](http://austen.cs.illinois.edu:5800/annotate?text=%22This%20is%20a%20sample%20sentence.%20I%27m%20happy.%22&views=))
Is there an easy way to recover char offsets from the json content? Do we have a function for this?

**Comment by danyaljj** [comment]
@mssammon  comments on this?

**Comment by mssammon** [comment]
There is a method in JsonSerializer: 
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/JsonSerializer.java#L50
It seems like this should be default behavior, but it is not:
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/JsonSerializer.java#L397
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/JsonSerializer.java#L393
how is the json file being generated?

**Comment by danyaljj** [comment]
Thanks. I think I found my answer here: 
https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/TokenUtils.java#L27
