### ISSUE TITLE
dependency (org.cogcomp.Datastore) not found

### ISSUE THREAD

**Issue by snigdhac** [CogComp/cogcomp-nlp#558]
I tried running the pipeline(3.1.30 and 33) locally, and the MentionAnnotator class seems to have the dependency ''org.cogcomp.Datastore", but throws a class not found error.  

I would also like to mention that I checked the contents of my local copy of files (".m2/repository/org/cogcomp/cogcomp-datastore/1.9.7/") and the files seem to have some weird "lastUpdated" appended to their names like "cogcomp-datastore-1.9.7.jar.lastUpdated" and "cogcomp-datastore-1.9.7.pom.lastUpdated". Not sure if this is relevant.

Here is the main function that produces this error:
public static void main(String[] args) throws IOException, AnnotatorException {
        AnnotatorService pipeline = PipelineFactory.buildPipeline(ViewNames.POS, ViewNames.LEMMA, ViewNames.MENTION);
        String text =  "This is a non-tokenized text. I like it.";
        TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "docId", "textId", text );
System.out.println(ta.getView(ViewNames.MENTION).getConstituents().size());
}

**Comment by mssammon** [comment]
just to make sure this is not a local repository problem: please run `mvn -U dependency:list` and try reinstalling your project.

**Comment by Slash0BZ** [comment]
@snigdhac I tried to run the main function you give above and I cannot reproduce the issue. Can you share more about your local environment?

**Comment by snigdhac** [comment]
I tried what @mssammon suggested and I get the error appended below (after doing "mvn clean"):

@Slash0BZ could you clarify what information you need from me when you say local environment?


Downloaded: http://cogcomp.cs.illinois.edu/m2repo/edu/cmu/cs/ark/ChuLiuEdmonds/1.0-SNAPSHOT/maven-metadata.xml (983 B at 3.3 kB/s)
[WARNING] The POM for edu.illinois.cs.cogcomp:illinois-prepsrl-model:jar:3.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading: http://cogcomp.cs.illinois.edu/m2repo/org/cogcomp/cogcomp-datastore/1.9.7/cogcomp-datastore-1.9.7.pom
Downloading: https://repo.maven.apache.org/maven2/org/cogcomp/cogcomp-datastore/1.9.7/cogcomp-datastore-1.9.7.pom
[WARNING] The POM for org.cogcomp:cogcomp-datastore:jar:1.9.7 is missing, no dependency information available
Downloading: http://cogcomp.cs.illinois.edu/m2repo/org/cogcomp/cogcomp-datastore/1.9.7/cogcomp-datastore-1.9.7.jar
Downloading: https://repo.maven.apache.org/maven2/org/cogcomp/cogcomp-datastore/1.9.7/cogcomp-datastore-1.9.7.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.544 s
[INFO] Finished at: 2017-09-26T10:07:16-04:00
[INFO] Final Memory: 14M/207M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project LocalPipelineTest: Could not resolve dependencies for project edu.illinois.cs.cogcomp:LocalPipelineTest:jar:1.0-SNAPSHOT: Could not find artifact org.cogcomp:cogcomp-datastore:jar:1.9.7 in CogcompSoftware (http://cogcomp.cs.illinois.edu/m2repo/) -> [Help 1]
[ERROR]

Here is a screenshot of my pom
![screen shot 2017-09-26 at 10 10 01 am](https://user-images.githubusercontent.com/2448805/30864865-e713dfe2-a2a2-11e7-94ac-59c603a1fc5e.png)

**Comment by Slash0BZ** [comment]
@snigdhac I just started a new project locally with the exact same maven pom file you provided above, and created one class that has the exact same main function you provided. I did `mvn install` and run the main class, no error/warning showed and the main function printed 1.

It's weird that your maven compiler looks for datastore:1.9.7, since it was a very old version and should not appear in any of the current version packages. Could  you check if have any local old cache?

The thing is datastore:1.9.7 was removed from m2repo since it's the old version. I think you can only find datastore:1.9.9 on m2repo. It's strange that the compiler still looks for 1.9.7

@danyaljj Please check if I got everything right. Thanks!

**Comment by snigdhac** [comment]
Hmm, let me try it again tomorrow on a different machine.

**Comment by danyaljj** [comment]
Also try the latest version I deployed this morning.

**Comment by snigdhac** [comment]
I tried pipeline version 3.1.34 and that seems to be working fine.
