### ISSUE TITLE
 IO Error while reading the file at hierarchies/20newsgroups/parentChildIdMap.txt

### ISSUE THREAD

**Issue by linxiexiong** [CogComp/cogcomp-nlp#595]
when running ./pipline/scripts/runWebserver.sh to start remote server, it comes out problem "ERROR DatalessAnnotatorUtils:104 - IO Error while reading the file at hierarchies/20newsgroups/parentChildIdMap.txt", while i can't find parentChildIdMap.txt this file.

**Comment by danyaljj** [comment]
Thanks! @shatu is working on this issue I believe. 
In the mean time you can use an older release.

**Comment by danyaljj** [comment]
Should be fixed now.
