### ISSUE TITLE
NESIM Api does not accept NE type

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#605]
Here in the readme, [NESIm](https://github.com/CogComp/cogcomp-nlp/tree/master/similarity#name-entities-comparison) should be able to receive types. 

For example, in the "Trump" example, we should be able to tell the system that he is a PERSON.

**Comment by sanjayss34** [comment]
Hi there! I have written a fix for this issue, and I would like to submit it for code review (as per Prof. Roth's request). However, I do not have permission to push to a new branch. Could you please grant it for me? Thanks!

**Comment by danyaljj** [comment]
Thanks! You gotta fork the project, and send a pull-request from your fork.

**Comment by sanjayss34** [comment]
Ok, thanks. I have opened a pull request.

**Comment by mssammon** [comment]
fixed in PR #625
