### ISSUE TITLE
sampleDocument.txt file?

### ISSUE THREAD

**Issue by ZeweiChu** [CogComp/cogcomp-nlp#619]
In dataless classifier, MemoryBasedESA.java requires a file named sampleDocument.txt, I am wondering if that could be provided.

**Comment by shatu** [comment]
sampleDocument.txt is only required if you are running MemoryBasedESA's main function. Technically, you can create any text file for the same. One such file has been provided here: https://github.com/CogComp/cogcomp-nlp/blob/master/dataless-classifier/src/main/resources/sampleDocument.txt
