### ISSUE TITLE
The original paper for SRL (Path-LSTM)

### ISSUE THREAD

**Issue by lan2720** [CogComp/cogcomp-nlp#620]
Hi, is the paper named as "Neural Semantic Role Labeling with Dependency Path Embeddings" (https://arxiv.org/abs/1605.07515)?
Thank you!

**Comment by lan2720** [comment]
And how can I use SRL (Path-LSTM), since I just see it on the website (http://nlp.cogcomp.org/). I wonder is there any API for it?

**Comment by danyaljj** [comment]
See this: https://github.com/CogComp/cogcomp-nlp/tree/master/external
