### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ZeweiChu** [CogComp/cogcomp-nlp#621]
When I run dataless classifier, MemoryBasedESA.java, I got java.lang.OutOfMemoryError: GC overhead limit exceeded . Is there any way to fix it?

**Comment by danyaljj** [comment]
You need to have a bigger memory.  As mentioned in the [readme](https://github.com/CogComp/cogcomp-nlp/tree/master/dataless-classifier#cogcomp-datalessclassifier) you have to have at least 10GB memory and make it available to your system.

**Comment by ZeweiChu** [comment]
In case anyone encounters the same problem. Need to set JVM heap size to more than 10G. I used -Xms 10G -Xmx 15G as additional JVM arguments.
