### ISSUE TITLE
mvn install on downloaded ner package

### ISSUE THREAD

**Issue by dimidd** [CogComp/cogcomp-nlp#623]
Hello,

I get the following error after downloading `illinois-ner` and running `mvn install`.

```[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for edu.illinois.cs.cogcomp:illinois-ner:[unknown-version]: Failure to find edu.illinois.cs.cogcomp:illinois-cogcomp-nlp:pom:3.0.23 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project edu.illinois.cs.cogcomp:illinois-ner:[unknown-version] (/Users/dimidd/Downloads/illinois-ner/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for edu.illinois.cs.cogcomp:illinois-ner:[unknown-version]: Failure to find edu.illinois.cs.cogcomp:illinois-cogcomp-nlp:pom:3.0.23 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException```

**Comment by cogcomp-dev** [comment]
You need to download the whole cogcomp-nlp package then run `mvn install -pl ner -am` to install the NER and its dependencies.

**Comment by dimidd** [comment]
Thank you, could you advise me where to download the whole package?

**Comment by cogcomp-dev** [comment]
the main repo is the one in which ner is located: `https://github.com/CogComp/cogcomp-nlp`

**Comment by dimidd** [comment]
I've downloaded the package from the [download link](http://cogcomp.org/page/download_view/NETagger) in the [README](https://github.com/CogComp/cogcomp-nlp/blob/master/ner/README.md). I understood (perhaps mistakenly) that the training data for the NER package isn't available, and that the downloaded package includes a pre-trained model. Otherwise, I would have cloned the repo and compiled from source.

**Comment by cogcomp-dev** [comment]
The training data can be found -- check the [cogcomp data page](http://cogcomp.org/page/resource_view/81) and the codebase supports retraining. But yes, the project dependencies include trained models for NER; cloning and compiling generates the feature extraction code but doesn't train any models.

**Comment by danyaljj** [comment]
@dimidd there are two alternatives: 
- You want to download the data and train your system: follow what @cogcomp-dev said. 
- If you only want to run the system, take a look at the [NER readme](https://github.com/CogComp/cogcomp-nlp/ner) or the [pipeline readme](https://github.com/CogComp/cogcomp-nlp/pipeline).

**Comment by dimidd** [comment]
@cogcomp-dev Thanks, I was referring to the Enron and Ontonotes training data.
@danyaljj Thanks, I'm indeed following the [NER README](https://github.com/CogComp/cogcomp-nlp/blob/master/ner/README.md), which states:

> To annotate plain text files, navigate to the root directory (illinois-ner/), and run the following commands (a plain text file is included in test/). NOTE: These commands assume you ran mvn install and mvn dependency:copy-dependencies, which create the ner binary in target/ and copies all dependency jars into target/dependency.

However, `mvn install` fails as reported above.
