### ISSUE TITLE
Pipeline SRL Verb Fails Weirdly

### ISSUE THREAD

**Issue by qiangning** [CogComp/cogcomp-nlp#656]
I'm trying to use pipeline to process some raw text and output a TextAnnotation with `verb SRL`. This is kind of urgent since I'm deploying my package as an online demo and the demo paper is due on 6/1. *Originally I was using curator, but the curator failed frequently (not always). Then I switched to pipeline but my pipeline always fails.* Any suggestions to workaround this would be great. @danyaljj @mssammon @HornHehhf  All I need is`verb SRL`.

I checkout the latest version of cogcomp-nlp. Here's the main function I use:

```
public static void main(String[] args) throws Exception{
        String text = "Helicopters patrol the temporary no-fly zone around New Jersey's MetLife Stadium Sunday, with F-16s based in Atlantic City ready to be scrambled if an unauthorized aircraft does enter the restricted airspace.";
        ResourceManager userConfig = new ResourceManager("pipeline/config/pipeline-config.properties");
        AnnotatorService pipeline = PipelineFactory.buildPipeline(userConfig);
        TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "", "", text );
        System.out.println();
    }
```

I got this error:
```
Connected to the target VM, address: '127.0.0.1:39575', transport: 'socket'
14:11:02 INFO  DepAnnotator:66 - Loading struct-perceptron-auto-20iter.model into temp file: tmp345673.model
14:11:03 INFO  SLModel:88 - Load trained Models.....
14:11:05 INFO  SLModel:97 - Load Model complete!
14:11:05 INFO  LabeledChuLiuEdmondsDecoder:72 - Loading cached PoS-to-dep dictionary from deprels.dict
14:11:06 ERROR BasicAnnotatorService:403 - The annotator for view SRL_VERB failed. Skipping the view . . . 
14:11:06 ERROR BasicAnnotatorService:403 - The annotator for view DEPENDENCY failed. Skipping the view . . . 
edu.illinois.cs.cogcomp.annotation.AnnotatorException: View 'NER_CONLL' cannot be provided by this AnnotatorService.
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:308)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:313)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:400)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:378)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:193)
	at edu.illinois.cs.cogcomp.pipeline.main.test.main(test.java:12)
edu.illinois.cs.cogcomp.annotation.AnnotatorException: View 'SHALLOW_PARSE' cannot be provided by this AnnotatorService.
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:308)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:313)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:400)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:378)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:193)
	at edu.illinois.cs.cogcomp.pipeline.main.test.main(test.java:12)

Disconnected from the target VM, address: '127.0.0.1:39575', transport: 'socket'

Process finished with exit code 0

```

**Comment by danyaljj** [comment]
You didn't say what's the content of `pipeline-config.properties`.

**Comment by qiangning** [comment]
FYI, when I use curator to add verb SRL for the same sentence, I also got an error:

```
public static void main(String[] args) throws Exception{
        String text = "Helicopters patrol the temporary no-fly zone around New Jersey's MetLife Stadium Sunday, with F-16s based in Atlantic City ready to be scrambled if an unauthorized aircraft does enter the restricted airspace.";
        /*ResourceManager userConfig = new ResourceManager("pipeline/config/pipeline-config.properties");
        AnnotatorService pipeline = PipelineFactory.buildPipeline(userConfig);
        TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "", "", text );*/
        AnnotatorService annotator = CuratorFactory.buildCuratorClient();
        TextAnnotation ta = annotator.createBasicTextAnnotation("","", text);
        annotator.addView(ta, ViewNames.SRL_VERB);
        System.out.println();
    }
```
```
Connected to the target VM, address: '127.0.0.1:38537', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:38537', transport: 'socket'
Exception in thread "main" edu.illinois.cs.cogcomp.annotation.AnnotatorException
	at edu.illinois.cs.cogcomp.curator.CuratorAnnotator.addView(CuratorAnnotator.java:55)
	at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:203)
	at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
	at edu.illinois.cs.cogcomp.core.datastructures.textannotation.TextAnnotation.addView(TextAnnotation.java:109)
	at edu.illinois.cs.cogcomp.curator.CuratorAnnotatorService.addView(CuratorAnnotatorService.java:257)
	at edu.illinois.cs.cogcomp.curator.CuratorAnnotatorService.addView(CuratorAnnotatorService.java:255)
	at edu.illinois.cs.cogcomp.pipeline.main.test.main(test.java:17)
```

**Comment by danyaljj** [comment]
Try dropping the config file: 
```java 
PipelineFactory.buildPipeline();
```

**Comment by qiangning** [comment]
```
String text = "He likes you.";
AnnotatorService pipeline = PipelineFactory.buildPipeline();
TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "", "", text );
```
The above gives me only TOKENS and SENTENCE views.

**Comment by danyaljj** [comment]
`PipelineFactory.buildPipeline(ViewNames.SRL_VERB)` should just suffice.

**Comment by qiangning** [comment]
It keeps asking me for new views. `PipelineFactory.buildPipeline(ViewNames.SRL_VERB)` says no POS, `PipelineFactory.buildPipeline(ViewNames.POS,ViewNames.SRL_VERB)` says no LEMMA... I added views according to the errors and ended up with `AnnotatorService pipeline = PipelineFactory.buildPipeline(ViewNames.POS,ViewNames.LEMMA,ViewNames.PARSE_STANFORD,ViewNames.SHALLOW_PARSE,ViewNames.NER_CONLL,ViewNames.SRL_VERB);`

Then I got this error: `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`

I have been using `-Xmx20g`.

**Comment by schen149** [comment]
I ran into similar problems a month ago. I think the VerbSRL also depends on `PARSE_STANFORD` view, so maybe try setting `useStanfordParse` to `true` in pipeline-config.properties?

Here are the required views for `SemanticRoleLabeler` (VerbSRL) class:  `[POS, NER_CONLL, LEMMA, SHALLOW_PARSE, PARSE_STANFORD]`

**Comment by qiangning** [comment]
@schen149 Exactly. You see I'm already using `AnnotatorService pipeline = PipelineFactory.buildPipeline(ViewNames.POS,ViewNames.LEMMA,ViewNames.PARSE_STANFORD,ViewNames.SHALLOW_PARSE,ViewNames.NER_CONLL,ViewNames.SRL_VERB);`

However, do you know why I'm receiving `java.lang.OutOfMemoryError: Java heap space` error although I'm using -Xmx20g?

**Comment by danyaljj** [comment]
20g is not enough, unfortunately. You probably need around 25g.

**Comment by qiangning** [comment]
FYI, the curator failed because of this error: `ServiceUnavailableException(reason:chunk unavailable:java.net.ConnectException: Connection refused (Connection refused))`

**Comment by qiangning** [comment]
28g is still not enough...

**Comment by qiangning** [comment]
@mssammon You know what, you saved my ass. Thanks very much! It works now. Now I see 
![image](https://user-images.githubusercontent.com/1971109/40746236-80ccf432-641f-11e8-8fc9-bb6c0600756e.png)

Does that mean chunker is back? What would I see if chunker is offline?

**Comment by qiangning** [comment]
Thanks.

Still, please keep this issue open for a while. Let me try it on server to see if increasing the memory size really solves this problem.

**Comment by benman1** [comment]
I have the same problem. Even if I assign lots of memory, it's failing. I haven't managed to get it to start so far. I tried Xmx2M to Xmx64G. I get something like this every time:

```bash
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000715300000, 1147142144, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1147142144 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/ben/prototyping/cogcomp-test/hs_err_pid9501.log
```

**Comment by mssammon** [comment]
@qiangning , @benman1 are you launching from the command line? if so, are you running on a shared server? what is the memory available on the host server?

**Comment by qiangning** [comment]
I was running from intellij on my local desktop, which has a 32G memory.

**Comment by mssammon** [comment]
I'm not sure what mechanism Intellij uses for managing memory, but it is possible that intellij itself has only a limited amount of memory to allocate that puts a ceiling on what you can specify for child processes that it launches.  You could try modifying the memory available to Intellij.

**Comment by mssammon** [comment]
e.g. https://www.jetbrains.com/help/idea/increasing-memory-heap.html

**Comment by qiangning** [comment]
I ran this on bronte, via the command line instead of intellij, and it works. Details are below.

The test code I use is this:
```
public class test {
    public static void main(String[] args) throws Exception{
        String text = "John likes you.";
        ResourceManager userConfig = new ResourceManager("config/pipeline-config.properties");
        AnnotatorService pipeline = PipelineFactory.buildPipeline(userConfig);
        TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "", "", text );
        System.out.println(ta.getAvailableViews());
    }
}
```

The config file is:
```
cacheDirectory  annotation-cache-test
throwExceptionIfNotCached   false
usePos	true
useDep	true
useLemma	true
useShallowParse	true
useNerConll	true
useNerOntonotes	false
useSrlVerb	true
useSrlNom	false
useCommaSrl	false
useQuantifier	false
useStanfordParse	true
useStanfordDep	false
useMention false
useRelation false
```
The output is:
```
[PARSE_STANFORD, SRL_VERB, NER_CONLL, LEMMA, TOKENS, SENTENCE, BROWN_CLUSTERS_1000, DEPENDENCY, CLAUSES_STANFORD, POS, SHALLOW_PARSE, DEPENDENCY_HEADFINDER:PARSE_STANFORD]
```
which looks good to me.

**The problem happens** if I'm not using our servers which often have more than 100G memories. When I created this issue, I was using my local desktop (linux; 32G memory), and it failed with the error message of `java.lang.OutOfMemoryError: Java heap space`. 

Now I tried to use my mac (16G memory), and it failed with the error message of `java.lang.OutOfMemoryError: GC overhead limit exceeded`, which means the garbage collector is spending too much time on freeing memories without much work being done.

**I think the conclusion is that memory consumption is so high that computers without a gigantic memory cannot handle it**. I monitored the VIRT (virtual memory) while running the program on bronte. I found that the peak value of VIRT is about 36G.

**I'd suggest a closure for this issue. However, we should**
- Make a special note in relevant readme files about this big memory consumption.
- Investigate (in a separate issue) why SRL consumes so much memory. For example, I have been wondering why NER is needed in SRL? It seems to me that NER is taking much memory.
