### ISSUE TITLE
java.lang.NullPointerException in LearningCurveMultiDataset

### ISSUE THREAD

**Issue by agusgun** [CogComp/cogcomp-nlp#674]
Here is the exception stack trace:
`java.lang.NullPointerException
	at edu.illinois.cs.cogcomp.ner.LbjTagger.LearningCurveMultiDataset.getLearningCurve(LearningCurveMultiDataset.java:167)
	at edu.illinois.cs.cogcomp.ner.LbjTagger.LearningCurveMultiDataset.getLearningCurve(LearningCurveMultiDataset.java:81)
	at edu.illinois.cs.cogcomp.ner.NerTagger.main(NerTagger.java:41)
`
I think this exception occured because `simpleTest.getOverallStats()[2] in line 157` have NaN value

**Comment by danyaljj** [comment]
How do you run the code? 

FYI @cowchipkid

**Comment by agusgun** [comment]
I just run train command using the default data. The train command is same with the train command in README. 
This is the command:
`java -Xmx8g -cp target/classes:target/dependency/* edu.illinois.cs.cogcomp.ner.NerTagger -train test/Test/0224.txt test/Test/0228.txt config/ner.properties`

**Comment by mayhewsw** [comment]
This is fixed in this commit: https://github.com/CogComp/cogcomp-nlp/pull/700/commits/ecf743197facc0cf950fcfa87c9ecfaf29d0a093

**Comment by agusgun** [comment]
Oke, I will close the issue
