### ISSUE TITLE
NER: fail to read training data to train model

### ISSUE THREAD

**Issue by yxd126** [CogComp/cogcomp-nlp#691]
Don't know who changed the code. When using NerBenchmark to train the model, the current NER cannot read training data from a folder to train a new model. I already find out the reason. 
The parameter order here is:
getLearningCurve(fixedNumIterations, trainDataPath, "-c", testDataPath, incremental);
(https://github.com/CogComp/cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/LbjTagger/LearningCurveMultiDataset.java#L76)

But the parameter order here is:
    public static void getLearningCurve(int fixedNumIterations, String dataFormat, String trainDataPath,
(https://github.com/CogComp/cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/LbjTagger/LearningCurveMultiDataset.java#L94)

'-c' and trainDataPath should change their position.

@mssammon  @cowchipkid

**Comment by cowchipkid** [comment]
I saw that as well, and I have fixed it. I discovered when testing the new set of changes to support multiple models in the same process space. I will check all that in today and issue a PR.

**Comment by yxd126** [comment]
I have checked again, and the issue has been solved.
