### ISSUE TITLE
cogcomp.cs.illinois.edu repo broken links

### ISSUE THREAD

**Issue by linux-handrey** [CogComp/cogcomp-nlp#698]
`cd ./ner`
`mvn -X compile`
output
`[DEBUG] Using transporter WagonTransporter with priority -1.0 for http://cogcomp.cs.illinois.edu/m2repo/
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for http://cogcomp.cs.illinois.edu/m2repo/
Downloading from CogcompSoftware: http://cogcomp.cs.illinois.edu/m2repo/org/apache/maven/plugins/maven-source-plugin/2.1.2/maven-source-plugin-2.1.2.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is 1281d17ac6f304c2f0b09ce2a510aa4a054d9651 from CogcompSoftware for http://cogcomp.cs.illinois.edu/m2repo/org/apache/maven/plugins/maven-source-plugin/2.1.2/maven-source-plugin-2.1.2.pom
[WARNING] Could not validate integrity of download from http://cogcomp.cs.illinois.edu/m2repo/org/apache/maven/plugins/maven-source-plugin/2.1.2/maven-source-plugin-2.1.2.pom
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, expected <!DOCTYPE but is 1281d17ac6f304c2f0b09ce2a510aa4a054d9651
`

**Comment by cogcomp-dev** [comment]
change target to http://cogcomp.org/m2repo in pom.xml file

**Comment by danyaljj** [comment]
Should be covered by #699
