### ISSUE TITLE
bring back test for BrownClusterFeatureExtractor 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#98]
The commented code in: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/765b4e789483817b68bdf320ec7d40266404e163/edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/factory/TestWordFeatureFactory.java#L152-L161

**Comment by mssammon** [comment]
@cttsai a reminder that has been assigned to you.
